server:
   port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: f5fb8087393ea938b458
            client-secret: 7cfc12184c67d28c7aee1e3d5446e85d56820261

#logging:
#  level:
#    org.springframework.security: DEBUG
# spring.security.oauth2. client.registration.github
  